/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package netfilm;

import javax.swing.JFrame;

/**
 *
 * @author Champeau
 */
public class NetFilm extends javax.swing.JFrame  {

    /**
     * Creates new form NetFilm
     */
    public NetFilm() {
        initComponents();
        et = EtatType.FILM;
        ec = EtatConnexion.DECONNECT;
        jPanel3.removeAll();
        jPanel3.add(jPanelDéconnecté1);
        jPanel3.repaint();
        jPanel3.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBAccueil = new javax.swing.JButton();
        jBFAffiche = new javax.swing.JButton();
        jBPSortie = new javax.swing.JButton();
        jBMCompte = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        filmsALAffiche1 = new netfilm.FilmsALAffiche();
        rechercheFilm1 = new netfilm.RechercheFilm();
        rechercheCinéma1 = new netfilm.RechercheCinéma();
        prochainesSorties1 = new netfilm.ProchainesSorties();
        pageFilm2 = new netfilm.PageFilm();
        pageCinéma1 = new netfilm.PageCinéma();
        jPanel3 = new javax.swing.JPanel();
        jPanelDéconnecté1 = new netfilm.JPanelDéconnecté();
        jPanelConnecté1 = new netfilm.JPanelConnecté();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(713, 662));

        jBAccueil.setText("Accueil");
        jBAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAccueilActionPerformed(evt);
            }
        });

        jBFAffiche.setText("Films à l'affiche");
        jBFAffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFAfficheActionPerformed(evt);
            }
        });

        jBPSortie.setText("Prochaines sorties");
        jBPSortie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPSortieActionPerformed(evt);
            }
        });

        jBMCompte.setText("Mon compte");
        jBMCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMCompteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAccueil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBFAffiche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPSortie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBMCompte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAccueil)
                    .addComponent(jBFAffiche)
                    .addComponent(jBPSortie)
                    .addComponent(jBMCompte))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel2.add(filmsALAffiche1, "card2");
        jPanel2.add(rechercheFilm1, "card3");
        jPanel2.add(rechercheCinéma1, "card4");
        jPanel2.add(prochainesSorties1, "card5");
        jPanel2.add(pageFilm2, "card6");
        jPanel2.add(pageCinéma1, "card7");

        jPanel3.setLayout(new java.awt.CardLayout());
        jPanel3.add(jPanelDéconnecté1, "card2");
        jPanel3.add(jPanelConnecté1, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBMCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBMCompteActionPerformed

    private void jBAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAccueilActionPerformed
        /**
         * Bouton Film à l'affiche cliqué.
         */
        
    }//GEN-LAST:event_jBAccueilActionPerformed

    private void jBFAfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFAfficheActionPerformed
        /**
         * Bouton Film à l'affiche cliqué.
         */
        jPanel2.removeAll();
        jPanel2.add(filmsALAffiche1);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jBFAfficheActionPerformed

    private void jBPSortieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPSortieActionPerformed
        /**
         * Bouton des prochaines sorties cliqué.
         */
        jPanel2.removeAll();
        jPanel2.add(prochainesSorties1);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_jBPSortieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private netfilm.FilmsALAffiche filmsALAffiche1;
    private javax.swing.JButton jBAccueil;
    private javax.swing.JButton jBFAffiche;
    private javax.swing.JButton jBMCompte;
    private javax.swing.JButton jBPSortie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private netfilm.JPanelConnecté jPanelConnecté1;
    private netfilm.JPanelDéconnecté jPanelDéconnecté1;
    private netfilm.PageCinéma pageCinéma1;
    private netfilm.PageFilm pageFilm2;
    private netfilm.ProchainesSorties prochainesSorties1;
    private netfilm.RechercheCinéma rechercheCinéma1;
    private netfilm.RechercheFilm rechercheFilm1;
    // End of variables declaration//GEN-END:variables


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*JFrame frame = new JFrame();
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.getContentPane().add(new Accueil());
                frame.pack();
                frame.setVisible(true);*/
                new NetFilm().setVisible(true);
            }
        });
    }
    private EtatConnexion ec;
    private EtatType et;
}
